---
apiVersion: v1
kind: Service
metadata:
    name: web-counter
spec:
  selector:
    app: web-counter
  type: LoadBalancer
  ports:
  - name: web-counter
    targetPort: 8000
    port: 8000
    nodePort: 30080
    protocol: TCP

